image: amazoncorretto:19 # Use the desired Java version

before_script:
  - yum install -y curl zip unzip # Install curl package using yum
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

stages:
  - build

build:
  stage: build
  script:
    - ./measure_old_version.sh > old_measurements.json
    - ./measure_new_version.sh > new_measurement.json
    - ./perfeval.sh init --benchmark-parser JMHJSONParser
    - ./perfeval.sh index-new-result --version 1.0 --path ./old_measurement
    - ./perfeval.sh index-new-result --version 2.0 --path ./new_measurement
    - ./perfeval.sh evaluate --t-test --junit-xml-output
