image: openjdk:21-jdk

before_script:
  - cd implementation
  - cd PerfEval

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle build # Build the project
  artifacts:
    paths:
      - build/libs/*.jar # Publish the built JAR file as an artifact

test:
  stage: test
  script:
    - gradle test # Run JUnit tests using Gradle

